server:
  port: 8003

spring:
  application:
    name: eureka-server-3
  security:
    user:
      name: lwj
      password: lwj

eureka:
  server:
    enable-self-preservation: false #关闭自我保护（生产环境不建议关闭）
    eviction-interval-timer-in-ms: 5000 #清理间隔，默认60000毫秒
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #注册中心不需要去检索服务，职责时维护服务实例
    fetch-register: false
    serviceUrl:
      defaultZone: http://lwj:lwj@127.0.0.1:8001/eureka/,http://lwj:lwj@127.0.0.1:8002/eureka/